// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nspmnimpogzvvqytpwpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zcG1uaW1wb2d6dnZxeXRwd3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzcwNTIsImV4cCI6MjA2MDU1MzA1Mn0.hUwL-Xj2_xov0noBdiajNiMb2CvNUFnSK_58-VpVcvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);